export const ACCESS_TOKEN_COOKIE_KEY = 'access_token';
export const REFRESH_TOKEN_COOKIE_KEY = 'refresh_token';
export const JWT_ACCESS_TOKEN_EXPIRATION_TIME_KEY =
  'JWT_ACCESS_TOKEN_EXPIRATION_TIME';
export const JWT_REFRESH_TOKEN_EXPIRATION_TIME_KEY =
  'JWT_REFRESH_TOKEN_EXPIRATION_TIME';
export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET';
